---
# tasks file for ansible-fio

- name: Check for supported OS
  ansible.builtin.fail:
    msg: >-
      This role supports Debian, Ubuntu, Fedora, CentOS, RHEL, Rocky, and AlmaLinux distributions.
      Current: {{ ansible_distribution }}
  when: ansible_distribution not in ['Debian', 'Ubuntu', 'CentOS', 'RedHat', 'Fedora', 'Rocky', 'AlmaLinux']

- name: Install fio packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ fio_packages }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
    install_recommends: false
  when: ansible_os_family == "Debian"
  retries: 3
  delay: 10

- name: Install fio packages (RHEL/CentOS/Rocky/AlmaLinux)
  ansible.builtin.yum:
    name: "{{ fio_packages }}"
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
  retries: 3
  delay: 10

- name: Install fio packages (Fedora)
  ansible.builtin.dnf:
    name: "{{ fio_packages }}"
    state: present
  when: ansible_distribution == "Fedora"
  retries: 3
  delay: 10
  ignore_errors: true
  register: fedora_dnf_result

- name: Install fio packages (Fedora) using raw dnf as fallback
  ansible.builtin.raw: dnf install -y {{ fio_packages | join(' ') }}
  when:
    - ansible_distribution == "Fedora"
    - fedora_dnf_result is failed
  register: fedora_raw_result
  retries: 2
  delay: 5

- name: Verify Fedora installation succeeded
  ansible.builtin.fail:
    msg: "Failed to install FIO on Fedora using both dnf module and raw dnf"
  when:
    - ansible_distribution == "Fedora"
    - fedora_dnf_result is failed
    - fedora_raw_result is failed

- name: Verify fio installation
  ansible.builtin.command: fio --version
  register: fio_version_check
  changed_when: false
  failed_when: fio_version_check.rc != 0
  retries: 2
  delay: 5
