---
# tasks file for ansible-fio

- name: Check for supported OS
  ansible.builtin.fail:
    msg: "This role only supports Ubuntu."
  when: ansible_distribution != 'Ubuntu'

- name: Install fio packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
    install_recommends: false
  with_items:
    - "{{ fio_packages }}"
