---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian12
    image: debian:12
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
  - name: ubuntu20
    image: ubuntu:20.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
  - name: ubuntu22
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
  - name: ubuntu24
    image: ubuntu:24.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
  - name: fedora42
    image: fedora:42
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/lib/systemd/systemd
  - name: rockylinux9
    image: rockylinux:9
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/lib/systemd/systemd
  - name: almalinux9
    image: almalinux:9
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/lib/systemd/systemd
  - name: el10
    image: ubi9:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/lib/systemd/systemd
provisioner:
  name: ansible
  inventory:
    host_vars:
      debian12:
        ansible_distribution: Debian
        ansible_distribution_release: bookworm
        ansible_distribution_major_version: "12"
      ubuntu20:
        ansible_distribution: Ubuntu
        ansible_distribution_release: focal
      ubuntu22:
        ansible_distribution: Ubuntu
        ansible_distribution_release: jammy
      ubuntu24:
        ansible_distribution: Ubuntu
        ansible_distribution_release: noble
      fedora42:
        ansible_distribution: Fedora
        ansible_distribution_major_version: "42"
      rockylinux9:
        ansible_distribution: Rocky
        ansible_distribution_major_version: "9"
      almalinux9:
        ansible_distribution: AlmaLinux
        ansible_distribution_major_version: "9"
      el10:
        ansible_distribution: RedHat
        ansible_distribution_major_version: "10"
verifier:
  name: ansible