---
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-debian:12}"
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 30; done"
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_distribution: "${MOLECULE_ANSIBLE_DISTRIBUTION:-Debian}"
        ansible_distribution_release: "${MOLECULE_ANSIBLE_RELEASE:-bookworm}"
        ansible_distribution_major_version: "${MOLECULE_ANSIBLE_VERSION:-12}"
        ansible_connection: docker
verifier:
  name: ansible