---
- name: Prepare
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Try to install Python3 with apt (Debian/Ubuntu)
      raw: |
        if command -v apt-get >/dev/null 2>&1; then
          apt-get update && apt-get install -y python3 python3-apt
        fi
      ignore_errors: true
      changed_when: false

    - name: Try to install Python3 with yum (RHEL/CentOS/Rocky/AlmaLinux)
      raw: |
        if command -v yum >/dev/null 2>&1; then
          yum install -y python3
        fi
      ignore_errors: true
      changed_when: false

    - name: Try to install Python3 and dnf dependencies (Fedora)
      raw: |
        if command -v dnf >/dev/null 2>&1; then
          dnf install -y python3 python3-libdnf5 python3-dnf
        fi
      ignore_errors: true
      changed_when: false

    - name: Check if Python3 is available
      raw: python3 --version
      register: python_check
      ignore_errors: true
      changed_when: false

    - name: Display Python version
      debug:
        msg: "Python3 check result: {{ python_check.stdout if python_check.stdout is defined else 'Not available' }}"