---
- name: Verify
  hosts: all
  become: false
  tasks:
    - name: Check if fio is installed using command -v
      ansible.builtin.shell: command -v fio || type fio || whereis fio
      register: fio_which
      changed_when: false
      ignore_errors: true

    - name: Try to run fio directly as a backup check
      ansible.builtin.command: fio --version
      register: fio_version_direct
      changed_when: false
      ignore_errors: true
      when: fio_which.rc != 0

    - name: Verify fio is available
      ansible.builtin.assert:
        that:
          - fio_which.rc == 0 or fio_version_direct.rc == 0
        fail_msg: "fio command not found - neither 'command -v fio' nor 'fio --version' worked"
        success_msg: "fio is properly installed"

    - name: Get fio version (using backup if main check failed)
      ansible.builtin.command: fio --version
      register: fio_version
      changed_when: false
      when: fio_which.rc == 0 or fio_version_direct.rc == 0

    - name: Use direct version check if main check failed
      ansible.builtin.set_fact:
        fio_version: "{{ fio_version_direct }}"
      when: fio_which.rc != 0 and fio_version_direct.rc == 0

    - name: Display fio version
      ansible.builtin.debug:
        var: fio_version.stdout
      when: fio_version is defined and fio_version.stdout is defined

    - name: Verify fio version output is not empty
      ansible.builtin.assert:
        that:
          - fio_version is defined
          - fio_version.stdout is defined
          - fio_version.stdout != ""
        fail_msg: "fio version command failed"
        success_msg: "fio version command works correctly"

    - name: Test basic fio functionality
      ansible.builtin.command: >
        fio --name=test --ioengine=libaio --iodepth=1 --rw=randread
        --bs=4k --direct=0 --size=1M --numjobs=1 --runtime=1
        --group_reporting --filename=/tmp/fio-test
      register: fio_test
      changed_when: false

    - name: Verify fio test completed successfully
      ansible.builtin.assert:
        that:
          - fio_test.rc == 0
        fail_msg: "fio test run failed"
        success_msg: "fio test run completed successfully"

    - name: Clean up test file
      ansible.builtin.file:
        path: /tmp/fio-test
        state: absent