---
name: CI
on:
  pull_request: {}
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: |
          pip3 install ansible ansible-lint yamllint
          
      - name: Lint YAML files
        run: yamllint .

      - name: Lint Ansible files
        run: ansible-lint

  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian12
          - ubuntu24
          - fedora42
          - rockylinux9
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: |
          pip3 install ansible molecule[docker] docker

      - name: Create roles directory and link current role
        run: |
          mkdir -p ~/.ansible/roles
          ln -s ${{ github.workspace }} ~/.ansible/roles/howtodojo.fio

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
